spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      mvc:
        routes:
          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/api/v1/product/**
            filters:
              - name: RequestHeaderToRequestUri
                args:
                  name: Authorization
          - id: search-service
            uri: lb://search-service
            predicates:
              - Path=/api/v1/search/**
            filters:
              - name: RequestHeaderToRequestUri
                args:
                  name : Authorization

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    registerWithEureka: true
    fetchRegistry: true

server:
  port: 8080
