spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**
        - id: category-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/category/**
        - id: sub-category-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/subCategory/**
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/v1/search/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/auth/**

        - id: address-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/address/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    registerWithEureka: true
    fetchRegistry: true

server:
  port: 8080
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
    root: INFO



