global:
  scrape_interval: 15s   # Her 15 saniyede bir scrape yapılacak
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
    metrics_path: /metrics
  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: [ 'ip:8081' ]
  - job_name: 'customer-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: [ 'ip:8082' ]
  - job_name: 'search-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: [ 'ip:8083' ]
  - job_name: 'basket-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: [ 'ip:8084' ]
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: [ 'ip:8085' ]
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: [ 'ip:8086' ]